from dataclasses import dataclass, field
from pyflot.configuration.config_base import ConfigBase


@dataclass
class PyflotConfigAnalysis(ConfigBase):
    ## CHOICES
    strat0 = "BT"
    strat1 = "BT-C"
    strat2 = "BT-Cf"
    strat3 = "BT-Cf->BT"
    strat4 = "BT-C->BT"
    strat5 = "SLOC"
    strat6 = "SLOC-C"
    strat7 = "SLOC-C->SLOC"
    strat8 = "SLOC-C->SLOC->BT"
    strat9 = "SLOC-C->SLOC->BT-Cf"
    strat10 = "SLOC-C->SLOC->BT-Cf->BT"
    strat11 = "SLOC-C->SLOC->BT-C"
    strat12 = "SLOC-C->SLOC->BT-C->BT"
    strat13 = "SLOC->BT"
    _strategies = tuple(
        [strat0, strat1, strat2, strat3, strat4, strat5, strat6, strat7, strat8, strat9, strat10, strat11, strat12, strat13]
    )

    ## OPTIONS
    verbosity: int = field(default=0, metadata={"help": "Verbosity of Poseidon.", "choices": (0, 1, 2, 3)})
    warnings: bool = field(default=True, metadata={"help": "Print warnings"})

    binary: str = field(
        default="./",
        metadata={"required": True, "help": "binary file absolute or relative path: DONT FORGET ./ if in same directory!"},
    )
    profilefile: str = field(
        default="profile.json",
        metadata={"help": """Profile phase dumps the JSON into profilefile into outputdir,
    Applying strat phase read into to create strat files."""},
    )
    readdir: str = field(default="", metadata={"help": "directory absolute path for all files read by tool analysis"})
    params: str = field(
        default="",
        metadata={"help": """This is for precising one application
                        parameter absolute or relative path.
                        (ex: ./inputs-2d-regt). Several arguments
                        should be written in between quotes: \"arg1 arg2 ...\" """},
    )
    profile_file: str = field(
        default="profile.json",
        metadata={"help": """Profile phase dumps the JSON into profilefile into outputdir,
    Applying strat phase read into to create strat files."""},
    )

    mergedtracefile: str = field(
        default="mergeCSVintoTrace.trace", metadata={"help": "Use merge CSV into trace file to build clusters."}
    )
    strategy: str = field(
        default="BT",
        metadata={
            "help": "Select the Strategy MultiStep to test: SLOC BT -C -Cf -> , to apply for searching tuning precision tuple",
            "choices": _strategies,
            "required": True,
        },
    )

    filtering: bool = field(
        default=False,
        metadata={
            "help": "If True, do clustering on SLOC (filter) before clustering on BACKTRACE when doing BT cluster step.",
        },
    )
    maxdepth: int = field(default=1, metadata={"help": "Clustering algorithm are hierarchical: pick a max depth."})
    dumpdir: str = field(default="./", metadata={"help": "directory absolute path for all files generated by tool analysis"})
    threshold: int = field(
        default=100000,
        metadata={
            "help": """Clustering algorithm result depend on graph edges,
            which depends on threshold (delta) for max timstamp difference.""",
        },
    )
    windowSize: int = field(
        default=2,
        metadata={
            "help": """Clustering algorithm result depend on graph edges,
            which depends on window size: how many nodes are allowed to have edges together?""",
        },
    )


@dataclass
class PyflotConfigMergeCsvIntoTrace(ConfigBase):
    with_check: bool = field(default=False, metadata={})
    dumpdir: str = field(default="./", metadata={})
    directory: str = field(default="./profile/", metadata={})


@dataclass
class PyflotConfigProfile(ConfigBase):

    binary: str = field(
        default="./",
        metadata={"required": True, "help": "binary file absolute or relative path: DONT FORGET ./ if in same directory!"},
    )
    params: str = field(default="", metadata={})
    ptunerdir: str = field(default="./", metadata={})
    stratfile: list[str] = field(
        default=[], metadata={"help": "List of json files containing either generated strategies and/or strategies to apply."}
    )
    outputfile: str = field(
        default="stdoutAndstderr",
        metadata={"help": """Stdout and stderr are dumped into:
    /path/to/outputdirectory/outputfile_profile.txt or ./ptuner_stratCOUNT_DATE_outputfile.txt"""},
    )
    profilefile: str = field(
        default="profile.json",
        metadata={"help": """Profile phase dumps the JSON into profilefile into outputdir,
    Applying strat phase read into to create strat files."""},
    )
    onlyProfile: bool = field(
        default=False,
        metadata={
            "help": """Choose to do only profiling no strategy generation,
    no applying strategy. One execution.""",
        },
    )
    onlyGenStrat: bool = field(
        default=False,
        metadata={
            "help": """Choose to do only strategies generation based on existing profiling.
    No application execution here.""",
        },
    )
    onlyApplyingStrat: bool = field(
        default=False,
        metadata={
            "help": "Choose to do only applying strategy. These MUST already have been generated.",
        },
    )
    movePLTdir: bool = field(
        default=False,
        metadata={
            "help": "Choose to move plt directories according to strategy number.",
        },
    )
    execAllStrat: bool = field(
        default=False,
        metadata={
            "help": "Exec all strategies even when a valid one is found",
        },
    )
    verif_text: str = field(
        default="VERIFICATION SUCCESSFUL",
        metadata={
            "required": True,
            "help": "Text searched in output to verify the code executed without accuracy error",
        },
    )
